version: '3.3'

services:
 backend:
  container_name: pizzeria-back
  build: .
  environment:
    - RETRIEVAL_MODE=${RETRIEVAL_MODE}
    - DB_CONNECTION_STR=mongodb://db-back:27017
  volumes:
    - .:/input
  links:
    - db
 db:
  image: mongo:latest
  container_name: db-back
  ports:
    - "27017:27017"